### PR TITLE
Add support for generic methods under interop

### PR DESCRIPTION
**Pull request by source-transformer**
add support for generic methods

### CODE REVIEW

**Review by lahma — CHANGES_REQUESTED** [review]
Mostly stylistic issue, tabs seems to running wild again. Also could you add description to PR what is to be expected?

**Comment by lahma** [comment]
If you rebase against main you should get `.editorconfig` that should guide your editor to use spaces over tabs, maybe that helps.

**Comment by source-transformer** [comment]
no problem for switching tabs to spaces - each time I do it (use tabs instead of spaces) - it is accidental. The convention just differs from the other projects I work in - so my editor defaults to tabs - I've grabbed the editor config - will try updating those individual spots you mentioned - see if the editor does the right thing.  In case it is of interest I'm using Visual Studio Preview/2022 on a mac.

**Review by lahma — APPROVED** [review]
I did small cleanup, there were still some tabs left and made new TypeConverter method internal.

**Pull request merged**
