### PR TITLE
fix: make `IConstructor` public again

### PR DESCRIPTION
**Pull request by viceice**
Make `IConstructor` public again until a better solution is found

- #1141
- #1144

### CODE REVIEW

**Comment by viceice** [comment]
@lahma @sebastienros  Are you ok with that solution?

**Comment by lahma** [comment]
I think I pondering with this one was left in the state of "Why not use a TypeReference" for this one... Probably need to check again with some thought at some point...

**Comment by viceice** [comment]
> I think I pondering with this one was left in the state of "Why not use a TypeReference" for this one... Probably need to check again with some thought at some point...

Ok, but how to with the uuid scenario? I'm happy to use another compatible solution if you can guide me.

**Comment by viceice** [comment]
I'll give it a try, need a couple of days to fine some time.

**Comment by viceice** [comment]
I no longer need this

**Pull request closed without merging**
