### PR TITLE
New interpreter engine

### PR DESCRIPTION
**Pull request by lahma**
This is a new way of interpreting Esprima AST I'm playing with.

* replace switch/case and if else with polymorphism
* each AST node is wrapped with Jint equivalent that tried to optimize the use case and cache values
* some new smarts about context and trying to do less when literals etc present

Let's see where this goes, might be better, might be worse. The new model is easier to reason with for me, and it should offer some performance benefits when the stateful smarts are tweaked.

### CODE REVIEW

**Comment by lahma** [comment]
Here's some current numbers. As you could predict, the less the JS does (smaller file) the bigger the penalty is. Whenever AST nodes are reused it should benefit. Still pondering whether reverting to old switch of type calling without virtual method invocation would be faster.

## Esprima.Benchmark.DromaeoBenchmark

| **Diff**|Method|FileName|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Run|dromaeo-3d-cube|72.88 ms|1285.7143|285.7143|-|7287.42 KB|
| **New** |	|	| **66.26 ms (-9%)** | **1250.0000 (-3%)** | **250.0000 (-13%)** | **-** | **7415.19 KB (+2%)** |
| Old |Run|dromaeo-core-eval|15.77 ms|62.5000|-|-|297.74 KB|
| **New** |	|	| **12.30 ms (-22%)** | **78.1250 (+25%)** | **15.6250** | **-** | **352.18 KB (+18%)** |
| Old |Run|dromaeo-object-array|158.28 ms|42000.0000|1750.0000|750.0000|177637.18 KB|
| **New** |	|	| **149.42 ms (-6%)** | **42000.0000 (0%)** | **1750.0000 (0%)** | **750.0000 (0%)** | **177655.08 KB (0%)** |
| Old |Run|droma(...)egexp [21]|865.84 ms|48000.0000|27000.0000|17000.0000|406120.11 KB|
| **New** |	|	| **813.39 ms (-6%)** | **51000.0000 (+6%)** | **31000.0000 (+15%)** | **21000.0000 (+24%)** | **413388.13 KB (+2%)** |
| Old |Run|droma(...)tring [21]|1,163.67 ms|219000.0000|176000.0000|174000.0000|1394013.53 KB|
| **New** |	|	| **1,146.59 ms (-1%)** | **217000.0000 (-1%)** | **175000.0000 (-1%)** | **172000.0000 (-1%)** | **1392795.02 KB (0%)** |


## Jint.Benchmark.ArrayBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Slice|100|435.6 us|160.6445|-|-|659.38 KB|
| **New** |	|	| **457.8 us (+5%)** | **170.8984 (+6%)** | **-** | **-** | **700.78 KB (+6%)** |
| Old |Concat|100|496.2 us|175.7813|-|-|723.44 KB|
| **New** |	|	| **534.9 us (+8%)** | **188.4766 (+7%)** | **-** | **-** | **772.66 KB (+7%)** |
| Old |Unshift|100|18,750.0 us|3562.5000|-|-|14671.88 KB|
| **New** |	|	| **18,476.6 us (-1%)** | **3593.7500 (+1%)** | **-** | **-** | **14823.44 KB (+1%)** |
| Old |Push|100|10,026.3 us|343.7500|-|-|1437.5 KB|
| **New** |	|	| **9,181.1 us (-8%)** | **390.6250 (+14%)** | **-** | **-** | **1617.97 KB (+13%)** |
| Old |Index|100|11,194.2 us|390.6250|-|-|1636.72 KB|
| **New** |	|	| **10,387.3 us (-7%)** | **437.5000 (+12%)** | **-** | **-** | **1832.81 KB (+12%)** |
| Old |Map|100|2,627.4 us|503.9063|-|-|2073.44 KB|
| **New** |	|	| **2,592.6 us (-1%)** | **527.3438 (+5%)** | **-** | **-** | **2164.84 KB (+4%)** |
| Old |Apply|100|580.1 us|188.4766|-|-|773.44 KB|
| **New** |	|	| **620.0 us (+7%)** | **201.1719 (+7%)** | **-** | **-** | **825.78 KB (+7%)** |
| Old |JsonStringifyParse|100|4,499.6 us|1273.4375|-|-|5233.59 KB|
| **New** |	|	| **4,554.7 us (+1%)** | **1289.0625 (+1%)** | **-** | **-** | **5303.13 KB (+1%)** |
| Old |FilterWithString|100|28,899.3 us|3406.2500|-|-|13962.5 KB|
| **New** |	|	| **26,836.5 us (-7%)** | **3406.2500 (0%)** | **-** | **-** | **14053.91 KB (+1%)** |


## Jint.Benchmark.ArrayStressBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Jint|20|545.6 ms|59000.0000|3000.0000|-|244.96 MB|
| **New** |	|	| **507.7 ms (-7%)** | **59000.0000 (0%)** | **3000.0000 (0%)** | **-** | **245.22 MB (0%)** |


## Jint.Benchmark.EvaluationBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Jint|20|669.2 us|117.1875|-|-|480.78 KB|
| **New** |	|	| **740.2 us (+11%)** | **139.6484 (+19%)** | **-** | **-** | **572.34 KB (+19%)** |


## Jint.Benchmark.StopwatchBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Jint|1|1.094 s|12000.0000|-|-|51.59 MB|
| **New** |	|	| **956.9 ms (-15%)** | **12000.0000 (0%)** | **-** | **-** | **51.61 MB (0%)** |


## Jint.Benchmark.UncacheableExpressionsBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Benchmark|500|265.8 ms|30500.0000|4500.0000|-|122.75 MB|
| **New** |	|	| **248.4 ms (-7%)** | **30333.3333 (-1%)** | **-** | **-** | **121.4 MB (-1%)** |

**Comment by ayende** [comment]
Just a note, one of the things that is important for us is the running of _very_ short scripts.
Typically less than 10 lines of code.

The catch is that the code may be doing stuff like `filter`, / `sort` on large arrays, but in general, they are very simple (property assignment, object building, etc).

How much do you think this change will help?

**Comment by lahma** [comment]
For RavenDB workloads it probably would make sense to optimize dense array operations to be closer to the metal. Now they go through adaptation layer that handles both dense and sparse, using `TryGetValue`/`SetIndexValue`, [like here](https://github.com/sebastienros/jint/blob/dev/Jint/Native/Array/ArrayPrototype.cs#L390). 

On similar note, I think that most of [your polyfills](https://github.com/ravendb/ravendb/blob/v4.1/src/Raven.Server/Documents/Patch/Polyfill.js) should already be implemented, which makes parsing and preparing some them for each engine unnecessary.  Also map on objects looks slow to interperet, would be faster on c# side where things are known beforehand, like key sizes etc - is this on hot path?

If your regular workload for engine usage differs a lot from my mapping benchmark above, I would love to hear about it.

**Comment by sebastienros** [comment]
@lahma are you stating that `UncacheableExpressionsBenchmark` is representative of RavenDB's load? If not it would make sense to add one or two scenarios that would be, so we can assess the impact of a change on these. We might even just call them "simple scripts" ;)

**Comment by lahma** [comment]
I think I need to play with the code a bit longer and tweak and find how to make things faster overall. I'm starting to know some grasp of Jint's internals which helps. I find the new design with class per statement/expression easier to reason with / maintain, and its should give us aformentioned benefit of adding some state/scenario knowledge and even trigger optimizations if wee see many calls.

I'll keep this PR updated and rebase against dev (where ES6 features land). I'm in no hurry with this 🙂

**Comment by lahma** [comment]
Some fresh numbers, I personally don't like the fluxuation of old test cases. Even though smallest script is expected to be a tad slower. Would love a computer separated from all things and producing stable numbers between runs. The numbers are against the original run above.

## Esprima.Benchmark.DromaeoBenchmark

| **Diff**|Method|FileName|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Run|dromaeo-3d-cube|72.88 ms|1285.7143|285.7143|-|7287.42 KB|
| **New** |	|	| **66.26 ms (-9%)** | **1250.0000 (-3%)** | **250.0000 (-13%)** | **-** | **7415.19 KB (+2%)** |
| Old |Run|dromaeo-core-eval|15.77 ms|62.5000|-|-|297.74 KB|
| **New** |	|	| **12.30 ms (-22%)** | **78.1250 (+25%)** | **15.6250** | **-** | **352.18 KB (+18%)** |
| Old |Run|dromaeo-object-array|158.28 ms|42000.0000|1750.0000|750.0000|177637.18 KB|
| **New** |	|	| **149.42 ms (-6%)** | **42000.0000 (0%)** | **1750.0000 (0%)** | **750.0000 (0%)** | **177655.08 KB (0%)** |
| Old |Run|droma(...)egexp [21]|865.84 ms|48000.0000|27000.0000|17000.0000|406120.11 KB|
| **New** |	|	| **813.39 ms (-6%)** | **51000.0000 (+6%)** | **31000.0000 (+15%)** | **21000.0000 (+24%)** | **413388.13 KB (+2%)** |
| Old |Run|droma(...)tring [21]|1,163.67 ms|219000.0000|176000.0000|174000.0000|1394013.53 KB|
| **New** |	|	| **1,146.59 ms (-1%)** | **217000.0000 (-1%)** | **175000.0000 (-1%)** | **172000.0000 (-1%)** | **1392795.02 KB (0%)** |


## Jint.Benchmark.ArrayBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Slice|100|435.6 us|160.6445|-|-|659.38 KB|
| **New** |	|	| **471.2 us (+8%)** | **170.8984 (+6%)** | **-** | **-** | **700.78 KB (+6%)** |
| Old |Concat|100|496.2 us|175.7813|-|-|723.44 KB|
| **New** |	|	| **596.7 us (+20%)** | **188.4766 (+7%)** | **-** | **-** | **772.66 KB (+7%)** |
| Old |Unshift|100|18,750.0 us|3562.5000|-|-|14671.88 KB|
| **New** |	|	| **18,063.4 us (-4%)** | **3593.7500 (+1%)** | **-** | **-** | **14823.44 KB (+1%)** |
| Old |Push|100|10,026.3 us|343.7500|-|-|1437.5 KB|
| **New** |	|	| **9,304.0 us (-7%)** | **390.6250 (+14%)** | **-** | **-** | **1617.97 KB (+13%)** |
| Old |Index|100|11,194.2 us|390.6250|-|-|1636.72 KB|
| **New** |	|	| **10,690.3 us (-5%)** | **437.5000 (+12%)** | **-** | **-** | **1832.81 KB (+12%)** |
| Old |Map|100|2,627.4 us|503.9063|-|-|2073.44 KB|
| **New** |	|	| **2,639.0 us (0%)** | **527.3438 (+5%)** | **-** | **-** | **2164.84 KB (+4%)** |
| Old |Apply|100|580.1 us|188.4766|-|-|773.44 KB|
| **New** |	|	| **632.1 us (+9%)** | **201.1719 (+7%)** | **-** | **-** | **825.78 KB (+7%)** |
| Old |JsonStringifyParse|100|4,499.6 us|1273.4375|-|-|5233.59 KB|
| **New** |	|	| **4,580.3 us (+2%)** | **1289.0625 (+1%)** | **-** | **-** | **5303.13 KB (+1%)** |
| Old |FilterWithString|100|28,899.3 us|3406.2500|-|-|13962.5 KB|
| **New** |	|	| **27,502.9 us (-5%)** | **3406.2500 (0%)** | **-** | **-** | **14053.91 KB (+1%)** |


## Jint.Benchmark.ArrayStressBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Jint|20|545.6 ms|59000.0000|3000.0000|-|244.96 MB|
| **New** |	|	| **510.1 ms (-7%)** | **59000.0000 (0%)** | **3000.0000 (0%)** | **-** | **245.22 MB (0%)** |


## Jint.Benchmark.EvaluationBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Jint|20|669.2 us|117.1875|-|-|480.78 KB|
| **New** |	|	| **720.8 us (+8%)** | **139.6484 (+19%)** | **-** | **-** | **572.34 KB (+19%)** |


## Jint.Benchmark.StopwatchBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Jint|1|1.094 s|12000.0000|-|-|51.59 MB|
| **New** |	|	| **944.3 ms (-16%)** | **12000.0000 (0%)** | **-** | **-** | **51.61 MB (0%)** |


## Jint.Benchmark.UncacheableExpressionsBenchmark

| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Benchmark|500|265.8 ms|30500.0000|4500.0000|-|122.75 MB|
| **New** |	|	| **236.7 ms (-11%)** | **30333.3333 (-1%)** | **-** | **-** | **121.4 MB (-1%)** |

**Comment by lahma** [comment]
OK I think I'm done with the tweaking for now. See above for the latest numbers. The smallest test case `EvaluationBenchmark` shows that the smallest script is a bit slower as expected, but all evaluation heavy cases (`DromaeoBenchmark`) are faster, even the "RavenDB" case `UncacheableExpressionsBenchmark` got faster due to targeted tweaks.

I feel new code is easier to profile and tweak. I've checked this branch against RavenDB source and only changes required is adding `ClrFunctionInstance` constructor parameter `name`. I'll leave the functional tests to DB folks.

**Comment by sebastienros** [comment]
LGTM

**Pull request merged**
