### PR TITLE
Implement Object.hasOwn

### PR DESCRIPTION
**Pull request by KurtGokhan**
This PR implements [Object.hasOwn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn)

It is still a [proposal](https://tc39.es/proposal-accessible-object-hasownproperty/#sec-object.hasown) ([Github](https://github.com/tc39/proposal-accessible-object-hasownproperty)) but most major browsers implement it already.

I don't know what is your usual procedure for testing this kind of stuff, but I got the tests from V8 source code.

### CODE REVIEW

**Comment by lahma** [comment]
I guess test262 repo already has test cases? They usually are the truth.

https://github.com/tc39/test262/tree/main/test/built-ins/Object/hasOwn

So basically copying them to correct place in test262 project's folder.

**Comment by KurtGokhan** [comment]
Should I copy them manually or is there a script to do it?

**Comment by lahma** [comment]
Manually currently. There's a PR to use npm, but now just manually copy of the folder.

**Comment by KurtGokhan** [comment]
Done.

**Comment by lahma** [comment]
Thanks, great work again.

**Pull request merged**
