### PR TITLE
Expose construction capabilities with code for JsArrayBuffer

### PR DESCRIPTION
**Pull request by lahma**

### CODE REVIEW

**Review by sfmskywalker — APPROVED** [review]
❤️

**Comment by sebastienros** [comment]
When @sfmskywalker is rich his first hire is @lahma

**Comment by sfmskywalker** [comment]
Yes, and you.

**Comment by sfmskywalker** [comment]
Awesome, thanks @lahma ! This enables some pretty nifty capabilities within Elsa when using JS expressions 🙏🏻

**Comment by lahma** [comment]
You are most welcome @sfmskywalker ! Thank you for sponsoring the project and giving feedback about value-adding features. The 3.1.3 release should soon pop up on NuGet, also containing this improvement.

**Pull request merged**
