### PR TITLE
fixed issue where the line number for exceptions in nested function …

### PR DESCRIPTION
**Pull request by andreykorolev**
…wasn't correct

### CODE REVIEW

**Comment by andreykorolev** [comment]
This fix is the same as #278 but without changes to line feeds and spaces

**Comment by andreykorolev** [comment]
When it will be available in nuget?

**Comment by andreykorolev** [comment]
could you please publish it to nuget?

**Comment by sebastienros** [comment]
Sorry for the delay, I just pushed a new version.

I will definitely try to find a way to integrate it with a custom myget feed for CI builds.

**Pull request merged**
