### PR TITLE
Adding ArrayLikeWrapper to support more interop array operations

### PR DESCRIPTION
**Pull request by ejsmith**
There are failing tests, but this approach does have less reflection going on. What are your thoughts @lahma ?

### CODE REVIEW

**Comment by lahma** [comment]
This is closer to what I had in mind. If you wish I can push commit(s) to this branch to tweak things.

**Comment by ejsmith** [comment]
Yeah, absolutely! Go for it.

**Comment by ejsmith** [comment]
I added you to the repository so you can push commits there if you like.

**Comment by lahma** [comment]
Just an update, I made some progress with bit of a refining proposal, hopefully have some time coming days to finish.

**Comment by lahma** [comment]
I've implemented some changes, all tests now green and also supports Newtonsoft array map operations that were failing earlier in OOTB experience because of problematic indexers. Custom configuration for non .NET 8 is now quite minimal.

**Comment by ejsmith** [comment]
Looks great!

**Pull request merged**
