### PR TITLE
Fix eval and function constructor failing for object literals with __proto__ prop

### PR DESCRIPTION
**Pull request by KurtGokhan**
Related to #598

Fixes weren't applied to Eval and Function Ctor before. 

Edit after tests: `Tolerant = true` breaks other tests. Do you know what may be a better solution?

### CODE REVIEW

**Comment by lahma** [comment]
I quickly checked just one test case and its contents:

```javascript
function testcase()
{
  try 
  {
    eval('"use strict"; var x = "\\17";');
    return false;
  }
  catch (e) {
    return (e instanceof SyntaxError);
  }
}
runTestCase(testcase);
```
So my hunch is that it's a strict mode issue. At least `PerformEval` has `strictCaller` parameter which you could use to choose between two different option setups (tolerant true/false), so maybe another static field for choosing between. Didn't dig deep into the issue so not sure.

**Comment by KurtGokhan** [comment]
I think this should be solved in Esprima.NET. Original esprima  also seems to have this bug.

**Comment by KurtGokhan** [comment]
Created sebastienros/esprima-dotnet#192

There is no need to change any code in Jint. Only tests.

But I noticed that by making `Tolerant = true` in the engine [in this PR](https://github.com/sebastienros/jint/pull/605/files#diff-28d7cd25ff148366bda545a8d3c4e400be429c5d2aa5be771d993d0a88c2d49dR40), some behaviors are not compliant with spec. Should we revert it? But it can be a breaking change.

**Comment by lahma** [comment]
Main branch has been updated with latest Esprima. Is there still an issue that we need to fix?

**Comment by KurtGokhan** [comment]
Let me test real quick.

**Comment by KurtGokhan** [comment]
Good to go. It is only tests.

**Review by lahma — APPROVED** [review]

**Comment by lahma** [comment]
Thanks for verifying!

**Pull request merged**
