### PR TITLE
Typed arrays

### LINKED ISSUE #168: No support for UInt8Array?
Doesn't appear that the runtime has a UInt8Array. Any chance we can add that? I can write the C# equivalent easily enough, but not sure how to plug it in.

### LINKED ISSUE #305: ArrayBuffer and TypedArray
Hi,
Is it possible to include either in main Jint or as an extension assembly support for ArrayBuffer and TypedArray ? Like Float32Array...
Thanks :)

### PR DESCRIPTION
**Pull request by lahma**
Typed arrays implementation.

fixes #305
fixes #168

### CODE REVIEW

**Comment by lahma** [comment]
Split ArrayBuffer and DataView to separate PR https://github.com/sebastienros/jint/pull/930

**Comment by devon-bfs** [comment]
Hi, This issue is marked resolve but unfortunately I still get the issue. I'm using the latest stable version. 2.11.58


image

**Comment by lahma** [comment]
You need to use the latest beta from NuGet, see main readme.

**Comment by devon-bfs** [comment]
Thank you for the response. The owners of the project don't want to use a beta version for production. Is there an ETA for when version 3 alpha will come out?

**Comment by lahma** [comment]
No ETA at the moment. The beta is more feature rich,  performant and has less bugs than 2.x series.

**Comment by lahma** [comment]
And alpha is considered less stable than beta 😉

**Comment by devon-bfs** [comment]
Thank you for your help. That answer might be enough to convince them

**Pull request merged**
