### PR TITLE
implemented conversion with newtonsoft json package

### PR DESCRIPTION
**Pull request by npenin**
Hi,

I implemented it because it is very easy to build/parse json from newtonsoft.json nuget package and collaboration with jint and newtonsoft seems a great advantage to me.

### CODE REVIEW

**Comment by fvaneijk** [comment]
Any way you could provide some unit tests?

**Comment by npenin** [comment]
Sure, is there a preferred place to put them ?
Already existing jint test project ? if yes, new file or existing file ?

**Comment by fvaneijk** [comment]
I would suggest a new file at: ...\Jint.Tests\Runtime\NewtonSoftJson.cs  if the extension becomes a standard part of Jint else put them in a new assembly of your choice.

**Comment by npenin** [comment]
here they are ;)

**Comment by fvaneijk** [comment]
thanks

**Comment by sebastienros** [comment]
I don't understand what the scope of the change is. Dare explaining ?

PS: @npenin and I wrote the first version of Jint together ;) Welcome back

**Comment by npenin** [comment]
Sure. WebAPI implements has Newtonsoft.Json  as a default wrapper. When you have for example a dynamic parameter in your web api, you actually get a JToken. As I am using this dynamic parameter directly in Jint, I needed this convesion. 
I could also have implemented a Web API Json converter using jint, but implementing a conversion to the "official" converter seemed more straight foreward to me and would open potentially more features as it provides also a json linq interface to build and read your json object.

**Comment by npenin** [comment]
Any chance you merge it in this week release ?

**Comment by sebastienros** [comment]
Actually accepting this would have Jint introduce external dependencies. Can we make this a plugin or at least find a way to accept such plugins ? For instance there is already a way to extend how objects are converted, did you try this?

**Comment by npenin** [comment]
I did it as a plugin as you say. I had just updated jint to introduce a missing AsDate to be consistent with other conversions. The whole conversion and dependency to Newtonsoft.Json is in another project. Don't you know me enough to know that I hate dirty code ? ;)

**Comment by sebastienros** [comment]
Cool, then please create another PR with just As/IsDate()

**Pull request closed without merging**
