### PR TITLE
Make Jint x86 and x64 compliant

### PR DESCRIPTION
**Pull request by postromantic**
Explicit struct layout field offsets removed. 
See #140 for discussion

### CODE REVIEW

**Comment by fvaneijk** [comment]
This seems like the best and simplest approach.

**Comment by sebastienros** [comment]
Isn't there a way to have different offsets based on a precompilation directive. I am sure it is provided as part of the build, and we could generate the different targets in the nuget package too. I remember this change improved the perf quite a bit and it would be sad to loose it.

**Comment by postromantic** [comment]
@sebastienros, originally this change was checked in with other caching/optimization code.Teamcity tests execution time of this pull request is even faster than with FieldOffsets. Do you have any memory profiler tests on that?

**Comment by sebastienros** [comment]
Then it's all good !

**Pull request merged**
