### PR TITLE
UnwrapIfPromise Call RunAvailableContinuations

### PR DESCRIPTION
**Pull request by scgm0**

### CODE REVIEW

**Comment by lahma** [comment]
Thank you!

**Comment by lahma** [comment]
I can't make head or tails about that comment.

**Comment by scgm0** [comment]
> I can't make head or tails about that comment.我对这个评论无法做出正确的判断。

Now that the matter is over, let’s wait and see if anyone will encounter problems because of this PR. It won’t be difficult to cancel it.

**Comment by lahma** [comment]
Next time maybe you can add some information to the pull request about you being unsure if your makes sense? Ideally every pull request should have descriptive description. From now on I'll try to to have extreme prejudice against the PRs...

**Comment by scgm0** [comment]
> Next time maybe you can add some information to the pull request about you being unsure if your makes sense? Ideally every pull request should have descriptive description. From now on I'll try to to have extreme prejudice against the PRs...下次也许你可以在拉取请求中添加一些关于你不确定你的想法是否有意义的信息？理想情况下，每个拉取请求都应该有描述性描述。从现在开始我会尽量对PR抱有极端的偏见......

ok, I really should have made it a draft, although it has been working on my own project for a while, but still not sure it's problem-free. . .

**Pull request merged**
