### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lahma**
Updated to better reflect features and current state, readability improvements. Please feel free to edit further and merge if/when looks good.

### CODE REVIEW

**Comment by lahma** [comment]
The rich diff mode in Files changed tab should render the new content quite nicely.

**Comment by sebastienros** [comment]
Looks great

- The very last section could be update
- Wondering if es5 should be listed the same way 2015, ... are in your list, even if just for a single check mark 

Even if you don't want to do any changes you should merge

**Comment by reuncc** [comment]
我发现,如果将this,传递到C#中的 ,过一段时间再传回来, 使用的时候 会有莫名其妙的 对象未实例化错误

**Comment by lahma** [comment]
> The very last section could be update

Last section needs an update or something that you refer as update should be moved?

**Comment by lahma** [comment]
Merged the initial version, we can surely further improve .

**Pull request merged**
