### PR TITLE
Add Options.InteropOptions.BuildCallStackHandler

### PR DESCRIPTION
**Pull request by scgm0**
A preliminary idea, this would allow one to modify the stack string generation, such as using a map of the source map.

### CODE REVIEW

**Comment by scgm0** [comment]
@lahma What do you think?

**Comment by lahma** [comment]
Probably would need better documentation and tests, `ValueStringBuilder` shouldn't be made public. If there's a solid use case for such configuration, why not.

**Comment by scgm0** [comment]
@lahma This is my first time writing a test, is it enough?

**Comment by lofcz** [comment]
> If there's a solid use case for such configuration, why not.

We've discussed this over at Acornima https://github.com/adams85/acornima/issues/6
This was previously requested here as well: https://github.com/sebastienros/jint/issues/490

This should warrant a sufficient use case. As hinted in the included test the feature aims to enable running transpiled TypeScript (and possibly other JS dialects) through Jint.

**Comment by lahma** [comment]
This is starting to look nice with the example use case described with tests! I'm traveling until Saturday but probably with minor tweaks we can merge.

**Comment by lofcz** [comment]
@scgm0 the PR is missing XML doc for the newly added public members, if you want I can add that for you.

**Comment by lahma** [comment]
One thing that came to mind is that would it be enough just to have callback `MapSourcePosition` which would by default just return same values back or be null and call stack builder would just call it and all string manipulation would remain in original call stack builder.

**Comment by scgm0** [comment]
> One thing that came to mind is that would it be enough just to have callback `MapSourcePosition` which would by default just return same values back or be null and call stack builder would just call it and all string manipulation would remain in original call stack builder.

The source map allows mapping function names(Although the typescript compiler does not seem to support it), and there may be users who prefer to use other formats for stack strings. For example, I like to use 4 spaces before `at` instead of 3.

**Comment by lahma** [comment]
The current format is node format I guess. We also need to consider if CallStackBuilder could be inherited and methods overridden, maybe configurable properties for indent. Need to tinker a bit

**Comment by lofcz** [comment]
@scgm0 I've opened a PR against your branch with the docs. Getting win/fw462 to pass tests requires resigning the Tests assembly due to the added dependency on `SourceMaps` I believe, win/net8 builds fine.

**Comment by scgm0** [comment]
> @scgm0 I've opened a PR against your branch with the docs. Getting win/fw462 to pass tests requires resigning the Tests assembly due to the added dependency on `SourceMaps` I believe, win/net8 is ok.

Thank you so much!

**Comment by scgm0** [comment]
I'm sorry, I'm using linux and still don't know why the win test fails (

**Review by lahma — APPROVED** [review]
Sorry it took so long, I rebased this and made minor adjustments, thank you for the contribution!

**Pull request merged**
