### PR TITLE
Improve STJ operability tests

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by sebastienros** [comment]
I am a real Jint dev now that I force push all my changes

**Review by lahma — APPROVED** [review]

**Comment by lahma** [comment]
I'm curious whether I should create paid-for high performance interop libraries for these without the need of reflection...

**Comment by sebastienros** [comment]
Sourcegen?

**Comment by hyzx86** [comment]
relate : https://github.com/sebastienros/jint/issues/1801

**Comment by lahma** [comment]
> Sourcegen?

To work against STJ probably won't need source generators, But one could use that for exposing any object type and attributes guiding the wrapper generation process.

**Comment by hyzx86** [comment]
Hi @lahma  ，

I added some unit tests here and found some differences between boolean values in `JsonObject` and variables assigned directly using `SetValue`.

https://github.com/sebastienros/jint/pull/1803

https://github.com/sebastienros/jint/pull/1803/files#diff-2987b5f3210d3f4a9ee6f2b52fefd414b4c797e01b62c6bae975f8db03cf4c5eR125-R131

**Pull request merged**
