### PR TITLE
Updates for v3 RTM

### PR DESCRIPTION
**Pull request by lahma**
* Update README.md

As generators and tweaks seem to be a forever project, might be easier to finally release the v3. I've gone through API from consuming viewpoint and I think it's quite near of not exposing too much and allows wiggle room in development - and there's always v4...

A week or so to ensure latest release doesn't break too much, or a year.. maybe.

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by lahma** [comment]
As @sebastienros basically gave us the go-live license, why not 🚀

**Comment by sebastienros** [comment]
Do you think your unfinished generators PR is not worth it in its current state. As in better not do anything than not support all quircks?

**Comment by lahma** [comment]
I think it can wait. Basically it suffers from the problem that it's now impossible from resume from *expression* state. Statements are easier now when it's just part of a list, but expressions are inside of a complex AST tree. The public APIs won't be affected from this when/if implemented.

**Comment by lahma** [comment]
This is what you get from Duke Nukem projects

image

**Pull request merged**
