### PR TITLE
FieldOffset fix to avoid TypeLoad exception in partial trust IIS level

### PR DESCRIPTION
**Pull request by postromantic**
Bugfix for #139: set +4 field offset to avoid overlapping

### CODE REVIEW

**Comment by ala53** [comment]
Unfortunately, this bugfix will only work on x86.

Can you put a patch up that does something like this:

```
        [FieldOffset(0)]
        private readonly bool _bool;

        [FieldOffset(0)]
        private readonly double _double;

        [FieldOffset(8)]
        private readonly ObjectInstance _object;

        [FieldOffset(8 + sizeof(IntPtr))]
        private readonly string _string;

        [FieldOffset(8 + sizeof(IntPtr) * 2)]
        private readonly Types _type;
```

That keeps us aligned to memory boundaries and handles different pointer sizes.

**Comment by ala53** [comment]
Sebastien, I think its a bad idea to merge it because if you run on an x64 os, the pointers will be 8 bytes and will cause an overlap with the _type variable (which will fail).

**Comment by postromantic** [comment]
@ala53, i agree, we should discuss it. 
#139 is x86 environment, so in theory assembly verification in x64 partial trusted env will fail.

__What's the reason of using explicit field offsets here?__ Avoid memory fragmentation? I don't see unmanaged code interaction where it's really important.
What about to use C++ union (FieldOffset=0 for all) https://msdn.microsoft.com/en-us/library/acxa5b99.aspx?f=255&MSPPError=-2147217396 ? Or use StructLayout.Sequental instead of explicit to let .NET align it in memory automatically?

**Comment by ala53** [comment]
We had an explicit layout as an optimization: we overlapped the two objects (string and ObjectInstance) which has now been reverted and also overlapped the bool and double. FieldOffset=0 for all won't work because .Net disallows overlapping memory pointers for objects and structs (already tried it).

**Comment by postromantic** [comment]
Yep, pure union doesn't work. I see 3 possible solutions:
1. Use Explicit struct layout with the following offsets: 0 0 8 16 20. There will be 'gaps' on x86, no overlapping.
2. Use Sequental struct layout and remove all field offset attributes. .NET will align fields automatically
3. Do not use struct layout attributes
What do you think?

**Comment by ala53** [comment]
We could maybe use nested structs:

In pseudocode:
```
[StructLayout]
public struct base {
[FO(0)]
public double d;
[FO(0)]
public bool b;
[FO(0)]
public int i;

public Types t;

[FO(sizeof double + sizeof Types)]
private base__internal bi;

public string s { get {return bi.s;}}

//and so on

private struct base__internal {
public string s;
public object o;
}

}
```

However, we'd need to be very careful to lay everything out on memory boundaries or we will lose any performance benefit we hope to gain.

**Comment by christianrondeau** [comment]
Agreed on the negligible gain; I believe you'll need to release a separate 32 bit and 64 bit versions of Jint to use that optimization; I personally suggest reverting that commit.

**Comment by postromantic** [comment]
PR #150 created to remove that optimization. I think Jint should be one solid PCL (without x86/x64 versions).

**Comment by christianrondeau** [comment]
Thanks @postromantic

**Pull request merged**
