### PR TITLE
ES6 destructuring

### PR DESCRIPTION
**Pull request by lahma**
Decided to tackle this in interim as this gives more test coverage again, also paying debt by releasing tests from ignore.

### CODE REVIEW

**Comment by sebastienros** [comment]
LGTM

How much do you follow the spec compared to your instincts/tests?

**Comment by lahma** [comment]
I had the spec there while implementing, but I did some shortcuts to make it perform better (spec always has the IsFunction, IsReference, etc metafunctions that are faster to follow by ideology, not creating/calling them). Here the change is quite isolated to expression handling (the new class), but when the time comes for let/const I think by-the-book might be easier.

Some-hundred new tests are passing, I'd say it's quite well according to spec 😉

**Comment by lahma** [comment]
And yes, the tests marked with "Esprima problem" are mostly about object spread which Esprima doesn't handle and is not part of the ES6, object spread is in draft version.

**Comment by sebastienros** [comment]
The hidden question was "did you just write it from tests", you answered, thanks.

**Pull request merged**
