### PR TITLE
allow overriding default clr type converter

### PR DESCRIPTION
**Pull request by ViceIce**
This pr fixes a regression of #625  which has made the clr type converter readonly.

### CODE REVIEW

**Comment by ViceIce** [comment]
My use case:

```cs
using System;
using Jint;
using Jint.Runtime.Interop;

namespace Scripting.Jint.Wrapper
{
    internal sealed class JintTypeConverter : DefaultTypeConverter
    {
        public JintTypeConverter(Engine engine) : base(engine)
        {
        }

        public override object Convert(object value, Type type, IFormatProvider formatProvider)
        {
            switch (value)
            {
                case string s when type == typeof(Guid) && Guid.TryParse(s, out var g):
                    return g;
            }
            return base.Convert(value, type, formatProvider);
        }
    }
}
```

**Comment by lahma** [comment]
Thank you for fixing and creating the test case to protect from such a regression in future.

**Comment by sebastienros** [comment]
Good job!

**Comment by ViceIce** [comment]
@sebastienros @lahma Any chances to get a new beta release?

**Comment by lahma** [comment]
Sorry for the delay, there was a release 5 days ago.

**Comment by ViceIce** [comment]
I know, thanks 👍

**Pull request merged**
