### PR TITLE
Improve method scoring logic between double and float

### LINKED ISSUE #1142: An incorrect double value is returned from a static method of the .NET type via interop
Hello!

In Jint version 3.0.0 Beta 2038 an incorrect double value is returned from a static method of the .NET type via interop. Moreover, this error occurs only in version for .NET Framework (everything works correctly in .NET Core). If you run the following console application:

```csharp
using System;

using Jint;
using Jint.Runtime.Interop;

namespace TestJint
{
    class Program
    {
        static void Main(string[] args)
        {
            var engine = new Engine();
            TypeReference mathTypeReference = TypeReference.CreateTypeReference(engine, typeof(Math));
            engine.SetValue("Math2", mathTypeReference);
            double result = engine.Evaluate("Math2.Max(5.37, 5.56)").AsNumber();

            Console.WriteLine("Result: {0}", result);
        }
    }
}
```

Previous version (version 3.0.0 Beta 2037) and current version for .NET Core output a correct result:

```
Result: 5,56
```

Current version for .NET Framework outputs an incorrect result:

```
Result: 5,55999994277954
```

### PR DESCRIPTION
**Pull request by lahma**
fixes #1142

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
You should try the magic button if you don't already
image

**Comment by lahma** [comment]
But if I enable auto merge it's harder to get some feedback 😉

**Comment by sebastienros** [comment]
Ah, forgot it doesn't require an approval (aspnet core does it, and it's not the best sometimes)

**Comment by lahma** [comment]
It's a though process to determine which changes are dead-simple and which are ones that require review, and on top of that steal your time to get the review 😉

**Pull request merged**
