### PR TITLE
Support explicit interface and hidden member of super class

### LINKED ISSUE #1611: Support explicit interface
**Is your feature request related to a problem? Please describe.**
```c#
    public interface I1
    {
        string Value();
    } 

    public class CI1 : I1
    {
        public I1 I1 { get { return this; } }
        public CI1 Self { get { return this; } }

        string I1.Value()
        {
            return "CI1 as I1";
        }

        public string Value()
        {
            return "CI1";
        }

        public void Run()
        {
            System.Console.WriteLine(this.I1.Value());
            System.Console.WriteLine(this.Self.Value());
        }
    }
```

```js
var ci1 = new CI1();
ci1.I1.Value(); // CI1 in js, but CI1 as I1 in c#
ci1.Self.Value(); // CI1 in js
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by viruscamp**
Close #1611 Support explicit interface and hidden member of super class
Add field `_clrType` to `ObjectWrapper`
Add `unwrapClr` helper method

### CODE REVIEW

**Review by lahma — APPROVED** [review]
Nice work and kudos for the great test coverage!

**Comment by CreepGin** [comment]
I think this PR is making all `public extern` members null. In my case, it's making a lot of Unity APIs inaccessible now.

**Comment by CreepGin** [comment]
The following Assertion will fail for this PR.

```cs
public class Container
{
    public Child Child => _child;

    Child _child = new Child();

    public BaseClass Get()
    {
        return _child;
    }
}

public class BaseClass
{
    public int index = 123;
}

public class Child : BaseClass { }

[Fact]
public void CustomTest()
{
    var engine = new Engine().SetValue("container", new Container());
    var res = engine.Evaluate(@"container.Child === container.Get()"); // These two should be the same object. But this PR makes `container.Get()` return a different object

    Assert.True(res.AsBoolean());
}
```

Also in the context of Unity, if Child and BaseClass contains `public extern` members, these will now be null if the object is retrieved via `container.Get()`.

**Comment by viruscamp** [comment]
@CreepGin , I think this behavior is as design.  
Maybe we can improve it a little:
```c#
Assert.False(engine.Evaluate(@"container.Child === container.Get()")); // as design
Assert.True(engine.Evaluate(@"container.Child == container.Get()")); // TODO
```

BTW, it provides `unwrap` method:
```c#
Assert.True(engine.Evaluate(@"container.Child === clrHelper.unwrap(container.Get())"));
```

**Comment by CreepGin** [comment]
So now the "wrapped" version of the object is making all the `public extern` members null. I'm assuming that's not by design right?

**Comment by viruscamp** [comment]
@CreepGin 
```c#
public interface I1
{
  string MethodFromInterface();
}
public class C1 : I1
{
  public extern string MethodFromInterface();
  public extern string MethodInClass();

  public static I1 InterfaceInstance => new C1();
}
```
Prepare js tests: ```engine.SetValue("C1", TypeReference.CreateTypeReference(engine, typeof(C1)));```
```javascript
var i1 = C1.InterfaceInstance; // typed ObjectWrapper with type I1
i1.MethodFromInterface(); // should success, if you cannot call it, fire an issue
i1.MethodInClass(); // failed as design, you wanna this works?
clrHelper.unwrap(i1).MethodInClass(); // should success, if you cannot call it, fire an issue
clrHelper.wrap(i1, C1).MethodInClass(); // it's better than just unwrap, like explicit conversion in C# ((C1)i1).MethodInClass();
```

**Comment by CreepGin** [comment]
```cs
i1.MethodInClass(); // failed as design, you wanna this works?
```

Yes. But maybe make explicit interface optional (via Jint.Options)? Or provide a way to disable it? (If this is already the case, please let me know; I must've missed it)

I do think the old behaviour should also be useful for a dynamic language like JS. (A good chunk of my codebase depends on it too)

**Pull request merged**
