### PR TITLE
IEnumerables regression

### PR DESCRIPTION
**Pull request by mattbrailsford**
Re-applying the bug fix in issue #11 as the commit 5680d3b8b74d558c60ada017f33bcfad2e8bf72d reverted the fix

### CODE REVIEW

**Comment by sebastienros** [comment]
It fails unit tests.

Can you add your own unit test too to show what you are trying to achieve?

**Comment by mattbrailsford** [comment]
Yea, sorry, noticed that. How do you run the unit tests locally? Doesn't
seem to integrate with the vs test runner.

**Comment by sebastienros** [comment]
It "just works" on my machine, I don't do anything special. You can disable the EcmaScript test project to make things faster as they shouldn't be impacted.
Maybe you need an extension in VS.Net to run them, the XUnit runner.

**Comment by mattbrailsford** [comment]
No probs. I'll take another look.

**Pull request closed without merging**
