### PR TITLE
Do not throw error immediately when receiving null Regex from Esprima 

### PR DESCRIPTION
**Pull request by KurtGokhan**
Sometimes Esprima will return null Regex. That means parsing did not fail, but the Regex is incompatible with C#.

With this PR, Jint will not fail during the parsing when such a Regex is received. It will only fail when that Regex is actually used. This way the user can handle the error, and also error can be avoided if that Regex is not used at all. 

See also: sebastienros/esprima-dotnet#173

Keeping this as draft until Esprima PR is merged and released. (Test will fail without the new Esprima)

### CODE REVIEW

**Comment by lahma** [comment]
@KurtGokhan 2.0.2 now available on NuGet.

**Comment by lahma** [comment]
Will this resolve #506 ?

**Comment by lahma** [comment]
I've updated main to have 2.0.2 as part of small bug fixing, new lib was required to get some test suite JS parsing working.

**Comment by KurtGokhan** [comment]
@lahma  that Regex is from [stylis](https://github.com/thysultan/stylis.js), which is the library I also noticed this issue. 

This PR will not fix the issue. But at least the parsing will pass. The regex will still fail on runtime if it is executed. In my case the regex is never executed so it works for me.

`code.Replace("[^]", "(?:.|\r|\n)")` is a legit fix for this case. But as I said, if we apply this hack blindly, we may break already valid regex like `[[^]`.

**Comment by lahma** [comment]
Cool, thanks for the clarification. We can merge?

**Pull request merged**
