### PR TITLE
Generate file version, remove Common.props

### LINKED ISSUE #492: Version is 0.0.0.0
From version 2.11.10 (on NuGet) and upwards, the version is 0.0.0.0.

This seems to be causing build issues due to not being able to resolve the dependency.

"C:\Program Files\dotnet\sdk\2.1.4\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Jint, Version=0.0.0.0, Culture=neutral, PublicKeyToken=2e92ba9c8d81157f, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors."

### PR DESCRIPTION
**Pull request by lahma**
Now NuGet package version still the same as before (containing beta), file version is 3.0.0.BuildVersion, assembly version is 3.0.0.0 (no binding redirects).

```
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;

// Assembly Jint, Version=3.0.0.0, Culture=neutral, PublicKeyToken=2e92ba9c8d81157f
// MVID: C05F92A7-20A6-44C7-9F76-28315D4690DB
// Assembly references:
// netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
// Esprima, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2e92ba9c8d81157f

[assembly: Extension]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: InternalsVisibleTo("Jint.Tests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100bf2553c9f214cb21f1f64ed62cadad8fe4f2fa11322a5dfa1d650743145c6085aba05b145b29867af656e0bb9bfd32f5d0deb1668263a38233e7e8e5bad1a3c6edd3f2ec6c512668b4aa797283101444628650949641b4f7cb16707efba542bb754afe87ce956f3a5d43f450d14364eb9571cbf213d1061852fb9dd47a6c05c4")]
[assembly: InternalsVisibleTo("Jint.Benchmark, PublicKey=0024000004800000940000000602000000240000525341310004000001000100bf2553c9f214cb21f1f64ed62cadad8fe4f2fa11322a5dfa1d650743145c6085aba05b145b29867af656e0bb9bfd32f5d0deb1668263a38233e7e8e5bad1a3c6edd3f2ec6c512668b4aa797283101444628650949641b4f7cb16707efba542bb754afe87ce956f3a5d43f450d14364eb9571cbf213d1061852fb9dd47a6c05c4")]
[assembly: TargetFramework(".NETStandard,Version=v2.0", FrameworkDisplayName = "")]
[assembly: AssemblyCompany("Sebastien Ros")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("Sebastien Ros")]
[assembly: AssemblyDescription("Javascript interpreter for .NET.")]
[assembly: AssemblyFileVersion("3.0.0.1947")]
[assembly: AssemblyInformationalVersion("3.0.0-beta-1947+320f831b74155dff020149ab531183f4631c8731")]
[assembly: AssemblyProduct("Jint")]
[assembly: AssemblyTitle("Jint")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/sebastienros/jint.git")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyVersion("3.0.0.0")]
```

fixes #492

### CODE REVIEW

**Comment by sebastienros** [comment]
After that we just need to remove the beta from the suffix to make it a stable release?

**Comment by lahma** [comment]
That's the technical version. Are we sure that the public API as great as it can get? I'd make sure that there's nothing eerily possibly to hurt us by needing to support. `EnterExecutionContext` etc. Then here's `Execute(...).GetCompletionValue()` vs `Evaluate()`. All kinds of things still public that might be internal until some cries about them.

**Comment by sebastienros** [comment]
What I meant was purely technical, not assuming taht we go stable once the Pr is merged. Just to know what the actions are to effectively have a stable version number.

**Review by sebastienros — APPROVED** [review]

**Comment by lahma** [comment]
Yes the version number 3.0.0.0 is just for binding. When we git RTM NuGet package is 3.0.0 with file version of say.. 3.0.0.345, assembly version 3.0.0. Next should be NuGet: 3.0.1, FileVersion: 3.0.1.456, Assembly: 3.0.1.0 . Or that just my thinking. 

* NuGet: marketing
* Assembly: logical version for bindings
* FileVersion (like InformationVersion): technical details to find the actual thing in VCS

**Comment by sebastienros** [comment]
So a stable release means always setting the version manually with the commit, right?

**Comment by lahma** [comment]
Yes, until there's some GitVersion or similar to help / sniffing the tag, like if tag matches "vX.Y.Z" and we are in master, extract numerical value and use it.

**Comment by sebastienros** [comment]
Can GitHub actions have parameters, like with a custom form? that would ask for the version number, and we wouldn't have to commit it in code.

**Comment by sebastienros** [comment]
Actually a custom tag syntax might be the best. So if a tag is added to the release/3.x branch, we can then ensure it starts with 3.x.y.z and publish the package.

**Comment by lahma** [comment]
I do [something similar in Quartz](https://github.com/quartznet/quartznet/blob/21f58325a2acbe11e5a8f3000d37ab46d93e3e6d/build.fsx#L18-L25). So if no tag suffix is preview and otherwise trust in code. Would probably be better to just pass the tag as Version like you suggested.

Can we merge this in interim?

**Comment by sebastienros** [comment]
merge

**Pull request merged**
