### PR TITLE
Update HourFromTime to handle pre 1/1/1970 #420

### PR DESCRIPTION
**Pull request by WestDiscGolf**
Update to how the calc for milliseconds is done. Went with DateTime processing as DateTimeOffset from milliseconds method is not available in all targetted platforms.

@sebastienros I was unsure where to put the unit test, please advise :-)

### CODE REVIEW

**Comment by sebastienros** [comment]
Please put the new tests beside the existing ones for dates, here https://github.com/sebastienros/jint/blob/dev/Jint.Tests/Runtime/EngineTests.cs#L1831

And look at the current CI job that failed because of regressions.

Thanks!

**Comment by WestDiscGolf** [comment]
Investigating about the test failures now (thought I'd run them all locally first *sigh*)

**Comment by WestDiscGolf** [comment]
Tests moved and updated for all tests to pass :)

**Comment by sebastienros** [comment]
Looking at your changes I realized the issues had to happen also on minutes and seconds. So I looked into the root cause and found the explanation. I created another PR.

**Comment by sebastienros** [comment]
Thanks for your work though.

**Comment by WestDiscGolf** [comment]
Np! Glad it was of some help even if it didn't make the cut ;-)

Thanks for the library!

**Pull request closed without merging**
